x-veld:
  code:
    about:
      description: "hard-coded evaluation of several spaCy2.2.4 models."
      topic:
        - "NLP"
        - "Machine learning"
        - "Named entity recognition"
    input:
      type: "folder"
      format: "custom"
      content:
        - "Named entity recognition gold data"
        - "Machine learning model"
      path: /veld/input/
      description: "This input is hard-wired to the apis spacy-ner repo and not made for generic usage."
    output:
      type: "file"
      format: "md"
      content: "evaluation report"
      path: /veld/output/reevaluations_all.md
      description: "evaluation report of the models from the apis spacy-ner repo."

services:
  veld:
    build: .
    volumes:
      - ./src/:/veld/code/
    command: python /veld/code/reevaluate_all_models.py

