x-veld:
  code:
    about:
      description: "hard-coded evaluation of several spaCy2.2.4 models."
      topics:
        - "NLP"
        - "Machine learning"
        - "Named entity recognition"

    inputs:
      volume: /veld/input/
      description: "This input is hard-wired to the apis spacy-ner repo and not made for generic usage."
      file_formats:
        - "pickle"
        - "txt"
        - "json"
        - "spacy model"
      contents:
        - "NER gold data"
        - "Machine learning model"
        - "NLP model"

    outputs:
      volume: /veld/output/
      description: "evaluation report of the models from the apis spacy-ner repo."
      file_formats: "md"
      contents: "evaluation report"

    environment:
      out_eval_result: 
        type: file
        volume: /veld/output/

services:
  veld:
    build: .
    command: python /veld/code/reevaluate_all_models.py
    volumes:
      - ./src/:/veld/code/
    environment:
      out_eval_result_file: null

